<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\User.Svc\User.Svc.csproj" />
    <ProjectReference Include="..\User.Db.MSSQL.EF\User.Db.MSSQL.EF.csproj" />
    <ProjectReference Include="..\User.Svc.Aio\User.Svc.Aio.csproj" />
  </ItemGroup>

</Project>
